language: node_js
node_js:
- '4.0'
- '8.0'
sudo: false
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  api_key:
    secure: emeA6MAuW+ZPLZoUITVdWfkWfHolCny9s4PiwroMoCiEKnFvTf7gUE5vrJmIMDNuq8iSatmC2Zi/t0fZT6Fn3xpwugfpeU0QLL1p9erJkZKeDJi98b/7xCaNBwseYa/pWMaF2f2Od31k2qWEj5JiTs5AjsouJXMplCuY2S/jPYo=
  file:
    - "parse-dutch.js"
    - "parse-dutch.min.js"
  on:
    tags: true
    node: '8.0'
